### ISSUE TITLE
Allowing custom parameters to be provided for MACS2 peak calling - ATACseq pipeline

### ISSUE THREAD

**Issue by anands1997** [russell-ryan-lab/ChIPseq_ATACseq_pipelines#3]
Hi, the current version of the ATACseq pipeline does not seem to provide an option to include additional custom parameters for peak calling with MACS2. Could this be added as an additional field in the config file?

**Comment by RussellJHRyan** [comment]
Anand, sorry for the delay on getting back to you on this. We are reviewing issues / feature requests from the beta launch, and will see what we can do about this. Thanks for testing the pipeline.

**Comment by rcavalcante** [comment]
We added this feature and it will be part of the next release.
