### ISSUE TITLE
ChIP test run issue

### ISSUE THREAD

**Issue by zxtzhangqian-float** [russell-ryan-lab/ChIPseq_ATACseq_pipelines#4]
Hi, Travis, Raymond 
When running the scripts for "chip_test.sh", most of the jobs are done and I got the following error:

igvtools count --includeDuplicates --pairs /nfs/turbo/umms-tomaszc/zxt/russel-pipeline/ChIPseq_ATACseq_pipelines/test_sra_chip_tf_pe/pruned/GM12878_Input.pruned.bam /nfs/turbo/umms-tomaszc/zxt/russel-pipeline/ChIPseq_ATACseq_pipelines/test_sra_chip_tf_pe/display_tracks/GM12878_Input.tdf hg19
[Wed Jul  1 17:48:49 2020]
Error in rule makeTagDirectory:
    jobid: 14
    output: /nfs/turbo/umms-tomaszc/zxt/russel-pipeline/ChIPseq_ATACseq_pipelines/test_sra_chip_tf_pe/tag/GM12878_NKRF
    shell:
        makeTagDirectory /nfs/turbo/umms-tomaszc/zxt/russel-pipeline/ChIPseq_ATACseq_pipelines/test_sra_chip_tf_pe/tag/GM12878_NKRF -keepAll -checkGC -genome hg19 /nfs/turbo/umms-tomaszc/zxt/russel-pipeline/ChIPseq_ATACseq_pipelines/test_sra_chip_tf_pe/pruned/GM12878_NKRF.pruned.bam
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 8419735

Error executing rule makeTagDirectory on cluster (jobid: 14, external: 8419735, jobscript: /nfs/turbo/umms-tomaszc/zxt/russel-pipeline/ChIPseq_ATACseq_pipelines/test_sra_chip_tf_pe/.snakemake/tmp.hbsixzfh/snakejob.makeTagDirectory.14.sh). For error details see the cluster log and the log files of the involved rule(s).
Submitted job 1 with external jobid '8419828'.
Waiting at most 60 seconds for missing files.
[Wed Jul  1 17:49:10 2020]
Finished job 1.
26 of 36 steps (72%) done
[Wed Jul  1 17:49:30 2020]
Finished job 4.
27 of 36 steps (75%) done

**Comment by RussellJHRyan** [comment]
Hi,

This is the first HOMER step, so I suspect there is something wrong with your HOMER installation or paths. At least one other user has had this problem. Can you post the contents of the log file for the makeTagDirectories step?

Best,

Russell

**Comment by zxtzhangqian-float** [comment]
Ok, we have to activate the conda env first to be able to set up homer.
